Задание 2. Добавлен README
gpb-it-factory/sokolov-telegram-bot pull request #2
Opened 2024-05-25 16:45 UTC by maks-x32

2024-05-27 15:47 UTC, konstantin-kozlovskiy requested changes

2024-05-27 15:47 UTC, konstantin-kozlovskiy commented on README.md
> +## Примечания
Разве всё что здесь написано, разве не относится к личным заметкам? Зачем это добавлять в ридми?

2024-05-27 18:39 UTC, maks-x32 commented on README.md
> +## Примечания
Да, это личные заметки. Хотелось побольше в readme написать. Согласен, это лишнее, удаляю.

2024-05-30 09:39 UTC, konstantin-kozlovskiy approved these changes

2024-05-30 17:26 UTC, merged